### ISSUE TITLE
Multibyte Language Support

### ISSUE THREAD

**Issue by dazebug** [velvia/msgpack4s#5] opened 2015-08-04 07:54 UTC
I don't know if there's a mistake in this code, but this code didn't work for me.
```scala
    val res: Seq[String] = Seq("안녕","안녕")
    implicit val codec: SeqCodec[String] = new SeqCodec()(StringCodec)

    println(msgpack.unpack(msgpack.pack(res)(codec))(codec))
```
ends with
```
Exception in thread "main" org.velvia.InvalidMsgPackDataException: Input contains invalid type value -120
	at org.velvia.msgpack.Codec$$anonfun$defaultUnpackFunc$1.apply(Codecs.scala:30)
	at org.velvia.msgpack.Codec$$anonfun$defaultUnpackFunc$1.apply(Codecs.scala:30)
	at org.velvia.msgpack.Codec$class.unpack(Codecs.scala:20)
	at org.velvia.msgpack.RawStringCodecs$StringCodec$.unpack(Codecs.scala:133)
	at org.velvia.msgpack.Format$.unpackSeq(Format.scala:204)
	at org.velvia.msgpack.CollectionCodecs$SeqCodec$$anonfun$3$$anonfun$apply$1.apply(CollectionCodecs.scala:17)
	at org.velvia.msgpack.CollectionCodecs$SeqCodec$$anonfun$3$$anonfun$apply$1.apply(CollectionCodecs.scala:17)
	at org.velvia.msgpack.Codec$class.unpack(Codecs.scala:20)
	at org.velvia.msgpack.CollectionCodecs$SeqCodec.unpack(CollectionCodecs.scala:10)
	at org.velvia.msgpack.package$.unpack(package.scala:12)
	at org.velvia.msgpack.package$.unpack(package.scala:53)
...
```
Any idea?
("안녕" means "Hello" in korea haha..)

**Comment by dazebug** [comment] 2015-08-04 07:55
```scala
    val res: Seq[String] = Seq("hello","hello")
    implicit val codec: SeqCodec[String] = new SeqCodec()(StringCodec)

    println(msgpack.unpack(msgpack.pack(res)(codec))(codec))
```
This works fine!

```scala
Vector(hello, hello)
```

**Comment by velvia** [comment] 2015-08-04 17:47
Yeah, it's a bug.  Found the cause -- not properly writing out the length
of raw bytes from unicode chars.  Will add a unit test and fix.

On Tue, Aug 4, 2015 at 12:55 AM, Choongjae Lee <notifications@github.com>
wrote:

>     val res: Seq[String] = Seq("hello","hello")
>     implicit val codec: SeqCodec[String] = new SeqCodec()(StringCodec)
>
>     println(msgpack.unpack(msgpack.pack(res)(codec))(codec))
>
> This works fine!
>
> Vector(hello, hello)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/velvia/msgpack4s/issues/5#issuecomment-127511226>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment] 2015-08-04 17:52
@dazebug thanks for reporting the issue.  Fix has been pushed to master.

**Closed by velvia** 2015-08-04 17:52 UTC
